better error msg
Co-authored-by: legaul-cisco <108479861+legaul-cisco@users.noreply.github.com>

diff --git a/scripts/launch-xrd b/scripts/launch-xrd
--- a/scripts/launch-xrd
+++ b/scripts/launch-xrd
@@ -246,7 +246,7 @@ while [[ $# -gt 0 ]]; do
         -- )
             shift
             if [[ $# == 0 ]]; then
-                echo "Invalid syntax: No args after --." >&2
+                echo "Error: Expected at least one arg after the '--' separator." >&2
                 bad_usage
             fi
             CTR_MGR_ARGS+=("$@")
